#
# An explanation of this commitlint configuration is provided in ./README.md.
#
# More information on how to configure commitlint rules can be found at
# https://commitlint.js.org/reference/rules-configuration.html
# https://commitlint.js.org/reference/rules.html
#
---
# Start from a basic set of rules defined here:
# https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional
extends:
  - "@commitlint/config-conventional"

# Override type-enum to just use types that are relevant to this project, and
# enforce formatting of first line of commit message to look like
#
#   <type>: Description starting with a capital letter
#
rules:
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - refactor
      - revert
      - test
  scope-empty: 
    - 2
    - always
  # Require initial capital letter
  subject-case:
    - 2
    - always
    - - sentence-case
      - start-case
      - upper-case
  body-max-line-length:
    - 2
    - always
    - 256  # permit, e.g., long URLs
