---
stages:
  - unit_test
  - integration
  - commit

go_test:
  stage: unit_test
  image: golang:1.19
  script:
    - go build ./...
    - go test -v -race ./...
    - if gofmt -d . | grep . ; then false ; else true ; fi

qemu_test:
  stage: integration
  image: debian:stable
  before_script:
    - apt update
    - apt install -qqy git golang-1.19 python3 qemu-system-x86 curl jq basez openssh-client
    - apt install -qqy --no-install-recommends python3-pip
    - pip install --break-system-packages --user virt-firmware
    - export PATH=/usr/lib/go-1.19/bin:$PATH
    - export PATH=$PATH:$HOME/.local/bin/
  script:
    - cd integration/
    - ./qemu.sh

commitlint:
  stage: commit
  image: node:alpine
  before_script:
    - apk add --no-cache git
    - npm install --save-dev @commitlint/config-conventional @commitlint/cli
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
